### ISSUE TITLE
3.x Roadmap

### ISSUE THREAD

**Issue by tbreuss** [getherbie/herbie#117]
*3.x Roadmap*

Todo:
- [ ] Implement a better (and simpler) page tree class
- [ ] Consistent handling for console commands as for the other extensions methods
- [ ] CSS and JS asset Twig functions doesn't work over inherited Twig templates
- [ ] Consider all http methods for route middlewares (not only GET)

Doing:
- [ ] Adminpanel for pages, data files and assets

Done:
- [x] Use query builder in `menu_list` twig function (2.x)
